### ISSUE TITLE
Failed to casting Gregorian to Persian Date.

### ISSUE THREAD

**Issue by raminmjj** [HEskandari/FarsiLibrary#10]
Hi.
If the current time is between 12:00 PM and 13:00 PM, the result will not be correct.
![2017-05-13 1](https://cloud.githubusercontent.com/assets/991847/26024426/0b6f5f7e-37e6-11e7-8d7a-545dd13c256d.png)
OS: Windows 10 64bit RS2

Thanks for your amazing work.

**Comment by HEskandari** [comment]
Thanks for reporting the issue. I'll look into it.
