### ISSUE TITLE
استفاده از تاریخ شمسی Devexpress

### ISSUE THREAD

**Issue by ghost1372** [HEskandari/FarsiLibrary#12]
سلام خسته نباشید ممنون بابت کنترل من میخوام از تقویم شمسی Devexpress
که شما  طراحی کردید داخل برنامم استفاده کنم ولی هرکاری کردم نتونستم اصلا این کنترل رو پیدا نمیکنم،
dll های FarsiLibrary.Utils و FarsiLibrary.Win.DevExpress.16.1 اصلا به تولباکس اضافه نمیشن
پروژه دموی شمارو هم نگا کردم اصلا چیزی متوجه نشدم.چطوری میتونم از تقویم خود devexpress
بصورت دراگ دراپ روی فرمم استفاده کنم؟یا حداقل یه اموزشی چیزی بگید ممنون

**Comment by ghost1372** [comment]
سلام مجدد، مشکل رو شناسایی کردم اینجا میگم شاید کسی به مشکل خورد بتونه اصلاح کنه
کل پروژه داره از دات نت فریمورک 4.6 استفاده میکنه اگر فریمورک پروژه شما پایین باشه نمیتونید از کامپوننت استفاده کنید و خطا میگیرید.
کامپوننت از نسخه 16.1 دواکسپرس داره استفاده میکنه اگه نسخه 17.1 دارید ممکنه خطا بگیرید که باید نسخه 17.1 رو از رفرنس حذف کنید
من با کمک سورس مشکلات رو برطرف و ریلیز جدید مطابق با 17.1 و فریمورک 4.5.2 گرفتم
الان بدون مشکل میتونم از تقویم شمسی استفاده کنم
ممنون بابت این کنترل عالی

**Comment by HEskandari** [comment]
همونطوری که متوجه شدید نسخه آخر روی 16.1 نوشته شده و به خاطری زیغ وقت به نسخه های جدید تر ارتقا داده نشده هنوز. اگر حجم تغییرات خیلی زیاد نباشه و تمایل داشته باشید میتونید Pull Request بفرستید که به نسخه جدیدتر ارتقا بدیمش. 

در مورد نسخه .NET Framework هم به خاطر ساپورت نسخه های قدیمی تر ، به نسخه های جدید تر ارتقا داده شد.

**Comment by ghost1372** [comment]
بله انشالله سعی میکنم یه درخواست پول ایجاد کنم
آقای اسکندری عزیز،همونطور که اطلاع دارید برای برنامه نویسی ویندوز اصلا تقویم شمسی وجود نداره و فک میکنم تقویم های شما تنها تقویم شمسی موجود باشن،اگر بتونید مناسبت ها و تعطیلات رسمی رو به تقویم اضافه کنید خیلی عالی میشه
من با کمک Devexpress
و رویداد CustomeDraw
تونستم حداقل تعطیلات رسمی رو توی تقویم بصورت رنگ قرمز مشخص کنم ولی مناسبت هارو نتونستم

**Comment by HEskandari** [comment]
مشکل اینجاست که مناسبت ها اکثرا تغییر میکنند (به علت تاریخ هجری قمری) ولی روشی رو که رفته اید درست است. به هر حال باید این اطلاعات از یک Provider بایید و بعد با استفاده از Custom Draw اونها رو Render کرد.

منظورتون رو از مناسبت ها متوجه نشدم؟ تفاوتش با تعطیلات رسمی چیه؟ فقط از نظر شکل ظاهری که چطور روی صفحه نمایش داده بشوند با هم متفاوت هستند ، نه؟

**Comment by ghost1372** [comment]
نه مناسبت ها ثابت هستند دیگه منتها هرسال باید یه اپدیت داد و مناسبت های جدید رو اصلاح کرد
منظورم اینه من فقط تونستم تعطیلات رسمی رو توی تقویم روزش رو به رنگ قرمز دربیارم
منظورم از مناسبت این هستش که اگه روی فلان تاریخ که تعطیل رسمی هست کلیک کنیم مناسبت اون روز رو نمایش بده مثلا 4 فروردین--> عید نوروز

**Comment by majnouni** [comment]
با سلام من الان از 
devexpress 17.2
استفاده میکنم ، امکانش هست کمک کنید که چه جوری از کامپوننت های شما استفاده کنم 
و آیا برای 17.2 به روز رسانی میکنید

**Comment by ghost1372** [comment]
من تو فورکی که انجام دادم با نسخه ۱۷.۲ هماهنگ کردم ازونجا دریافت کنید

**Comment by majnouni** [comment]
میشه کمک کنید که چه جوری میتونم دریافت کنم ؟
و چه جوری میشه به پروژه اضافه کرد ؟

**Comment by majnouni** [comment]
سلام مجدد ، من با سورس نرم افزار کلاس شما روی 17.1 جواب گرفتم ولی کامپوننت های 17.2 مشکل دارن با 
farsilibrary

**Comment by ghost1372** [comment]
سلام تا چند دقیقه نسخه هماهنگ با 17.2.3 قرار میدم
