### ISSUE TITLE
استایل دهی به کنترل تقویم و تاریخ

### ISSUE THREAD

**Issue by ghost1372** [HEskandari/FarsiLibrary#15]
سلام اقای اسکندری یکبار دیگه از کنترل خیلی خوبتون تشکر میکنم
من میخام از کنترل شما توی WPF
استفاده کنم منتها نحوه استفادش توی WPF خیلی پیچیده هست
البته اگه همون کنترل خام رو بخایم استفاده کنیم مشکلی نداره ولی چون استایل نداره خیلی بی روح و زشت هست
من بزور و زحمت تونستم نمونه شما  رو از پروژه بکشم بیرون و توی پروژه دیگه قرار بدم برای شما استایل مشکی داره
اگر ممکنه استایل هارو داخل خود کنترل قرار بدید با یه دستور بتونیم فراخوانی کنیم
البته توی wpf تازه کارم

**Comment by HEskandari** [comment]
نحوه استایل کردن این کنترلها با استفاده از Resource Dictionary هست
چند تا نمونه هست ، یکی داخل پروژه Sample ها
راه ساده تر استفاده از Expression Blend هست که به راحتی میتونید استایل ها رو تغییر بدید
