### ISSUE TITLE
مشکل نال بودن اعداد در ویندوز فرم

### ISSUE THREAD

**Issue by eafar1366** [HEskandari/FarsiLibrary#17]
با سلام
ممنون  از زحمتی که کشیدین
چرا دیت پیکر در وین فرم با vs 2015 اعداد رو null نشون میده 
مشکلی هست ؟

**Comment by ghost1372** [comment]
سلام میشه یه تصویری از مشکلتون قرار بدین؟

**Comment by HEskandari** [comment]
Closing, please reopen if still relevant.
