### ISSUE TITLE
مشکل بهم ریختن تاریخ بعد از وارد کردن تاریخ توسط کیبورد

### ISSUE THREAD

**Issue by MehdiCheshmi** [HEskandari/FarsiLibrary#18]
وقتی با کنترل xtradateedit تاریخ  توسط کیبورد ویرایش میشه تاریخ منتقل میشه به سال 773/12/11 و تاریخ معتبری شناخته نمیشه توسط ویندوز .
![image](https://user-images.githubusercontent.com/37826504/37950459-d008ced0-31ad-11e8-8766-a3b06596ee06.png)

**Comment by HEskandari** [comment]
چه تاریخی رو وارد میکنید؟ مقدار دقیقی رو که وارد میکنید مشخص کنید و همینطور چه نسخه ای از کنترل های FarsiLibrary و DevExpress رو استفاده میکنید؟

**Comment by HEskandari** [comment]
اصولا برای Parse کردن مقدار رشته به تاریخ این که روی چه  Culture برنامه در حال اجرا باشه مهمه.
در نسخه ویندوز ۷ به درستی کار میکنه و اینکه میگید تاریخ شمسی با کالچر انگلیسی کار نمیکنه طبیعیه.
در نسخه ویندوز ۱۰ تغییراتی که در خود ویندوز دادند که تاریخ فارسی را ساپورت کنن باعث میشه که حتی اگر کالچر در زبان انگلیسی باشه مقدار درست Parse بشه.

این که فقط موقع تایپ هم مشکل دارید باز هم طبیعیه چون موقع انتخاب از تقویم احتیاجی به Parse نیست.

**Comment by MehdiCheshmi** [comment]
یعنی این مشکل در ویندوز 7 قابل به حل شدن نیس؟ در ویندوز 7 سمپل خود شما هم این مشکل رو داره ! این امکان وجود نداره که مقدار ورودی کاربر تبدیل بشه به میلادی بعد پارس بشه که برنگرده به این تاریخ ؟

**Comment by HEskandari** [comment]
کالچر برنامه تون رو روی fa-ir ست کنید هم همین مشکل رو داره؟

**Comment by MehdiCheshmi** [comment]
اره تو ویندوز 7 کالچر کلا رو فارسی تنظیم شده که تاریخ رو به صورت شمسی نشون میده اما تو ویندوز 10 اگه کالچر رو انگلیسی باشه بازم مشکل ویندوز 7 رو داره !! من چیزی که فهمیدم همین بود که داره واسه تقویم میلادی داره ورودی شمسی ست میشه !! گفتم اگه بشه کلا به صورت پیش فرض تبدیل کنیم ورودی رو به میلادی بعد ست کنیم که نمایش باز به صورت شمسی نشون داده بشه !

**Comment by MehdiCheshmi** [comment]
من یه نمونه برنامه نوشتم و کالچر رویه فارسی تنظیم کردم تو ویندوز 10 مشکلی وجود نداشت ولی تو ویندوز هفت وقتی با کیبورد تاریخ وارد میشه بازم مشکل داره
 [http://uplod.ir/dogn5uyj993u/SamplePersianDate.rar.htm
](url)

**Comment by MehdiCheshmi** [comment]
جناب اسکندری نتیجه بررسی چی شد؟ تونستین نمونه برنامه رو دریافت کنید؟ @HEskandari

**Comment by HEskandari** [comment]
سلام

نه متاسفانه...فکر کنم فایل را با تاخیر دانلود کردم (نصب ویندوز ۷) و بعد که سعی به دانلود کردم پیغام میداد که فایل برای دانلود موجود نیست

**Comment by MehdiCheshmi** [comment]
این لینک جدید دانلود نمونه برنامه جناب اسکندری @HEskandari 
http://uplod.ir/6nppidw6qhx0/SamplePersianDate.rar.htm

**Comment by HEskandari** [comment]
بله تست شد. روی ویندوز ۷ همونطوری که توضیح دادید مشکل داره وقتی که Tab میزنید.

**Comment by MehdiCheshmi** [comment]
@HEskandari  راهکاری واسه حل این مشکل پیدا نشد جناب اسکندری؟

**Comment by EhsanFaghih** [comment]
@HEskandari , @MehdiCheshmi  برای این مشکل راه حلی پیدا نشد؟

**Comment by HEskandari** [comment]
نسخه مورد استفاده نسخه های قدیمی است و به دلیل نوع تغییرات به سادگی قابل تبدیل به نسخه های جدیدتر نیست.

**Comment by EhsanFaghih** [comment]
سلام متوجه منظورتون نشدم.
یعنی باید از نسخه جدید (2.7) استفاده کنم؟

**Comment by HEskandari** [comment]
@EhsanFaghih نه. مشکل مربوط به کنترل های DevExpress هست که نسخه استفاده شده مربوط به سال ۲۰۱۵ و ۲۰۱۶ هست. 
نسخه های مربوطه مال ۵-۶ سال پیش هست و امکان تغییر کنترل ها بر نسخه جدید تر وجود نداره. در نسخه های جدید تر بحث راست به چپ در خود کنترل ها حل شده و احتمالا این مشکل هم حل شده است ولی کد فعلی قابل انتقال به نسخه های جدید تر نیست.
