### ISSUE TITLE
Update to Devexpress v18

### ISSUE THREAD

**Issue by parsisan** [HEskandari/FarsiLibrary#20]
سلام و خسته نباشید.
ممنون از زحمات شما و @ghost1372 
ممنون میشم طریقه ی استفاده رو به صورت ساده بیان کنین (این که به عنوان رفرنس کتابخونه ی شما رو اضافه کنیم و کالچر رو رو فارسی تنظیم کنیم و ...)
 و اینکه برای آپدیت به نسخه ی ۱۸ چه کار لازم هست تا خودمون انجام بدیم.

سپاس

**Comment by HEskandari** [comment]
پروژه های دمو رو ببینید توضیحات باید کافی باشه. 
برای نسخه ۱۸ دواکسپرس یک PR اینجا هست که فرستاده شده.
بعد از نهایی شدن و تست شدن میتونید پکج هاش رو از نوگت بگیرید و استفاده کنید.

**Comment by HEskandari** [comment]
There are currently no plans to support newer versions of DevExpress.
