### ISSUE TITLE
Exception in FaMessagebox when set message box null

### ISSUE THREAD

**Issue by navid-dada** [HEskandari/FarsiLibrary#25]
I am getting this Exception 

> Key cannot be null.\r\nParameter name: key

from faMessagebox by this code:
`var msg = FAMessageBoxManager.CreateMessageBox(null);`
 `msg.Text = "آیا مایل به حذف این رکورد هستید ؟";`
 `msg.Caption = "هشدار";`
 `msg.Icon = FarsiMessageBoxExIcon.Question;`
 `msg.AddButtons(MessageBoxButtons.OKCancel);`
` var result = msg.Show();`

**Comment by HEskandari** [comment]
The exception does state that the Key can not be null. Look at the docs to see how to use the component.
