### ISSUE TITLE
نحوه افزودن کنترل تقویم فارسی دواکسپرس به تولباکس 

### ISSUE THREAD

**Issue by MrSarrafi** [HEskandari/FarsiLibrary#26]
سلام
FarsiLibrary.Win.DevExpress.16.1.dll به تولباکس اضافه نمیشه.
چی رو باید اد کنم پس؟
میخوام کنترل تقویم فارسی دواکسپرس به تولباکس کامپوننت هام اضافه شه و به فرمم بندازم.
چیکار باید بکنم؟
سوال بعدی هم : 
میشه دات نت 4 کرد پروژه را؟
ممنون

**Comment by HEskandari** [comment]
Closing, please re-open if this is still relevant.
