### ISSUE TITLE
devexpress 21

### ISSUE THREAD

**Issue by zarinafzar** [HEskandari/FarsiLibrary#29]
سلام.
من سورس شما را به نسخه 21 ارتقا دادم. چطور میتونم توی گیت اونو پوش کنم؟ در همینجا

**Comment by HEskandari** [comment]
@noawar باید روی یک Fork انجام بدید و بعد یک PR بفرستید.

**Comment by MohMehrnia** [comment]
> سلام.
> من سورس شما را به نسخه 21 ارتقا دادم. چطور میتونم توی گیت اونو پوش کنم؟ در همینجا

من تبدیل رو انجام دادم اما وقتی تقویم باز میشه امکان انتخاب هیچ تاریخی نیست، شما به این مشکل بر نخورید

**Comment by noawar** [comment]
> > سلام.
> > من سورس شما را به نسخه 21 ارتقا دادم. چطور میتونم توی گیت اونو پوش کنم؟ در همینجا
> 
> من تبدیل رو انجام دادم اما وقتی تقویم باز میشه امکان انتخاب هیچ تاریخی نیست، شما به این مشکل بر نخورید

از dateEdite استفاده کنید

**Comment by MohMehrnia** [comment]
منظورتون Dateeditخود Devexpress هست

**Comment by mahdi62-dev** [comment]
سلام.
    من هم  تبدیل رو انجام دادم اما وقتی تاریخ رو انتخاب میکنم ، تاریخ میلادی رو نشون میده 
توی dateedit اینطور میشه

**Comment by HEskandari** [comment]
I'm closing this issue. Please send a PR if you can, otherwise there's currently no plans to update to a newer version of DevExpress.

**Comment by MohMehrnia** [comment]
> ```
>     سلام.
> من هم  تبدیل رو انجام دادم اما وقتی تاریخ رو انتخاب میکنم ، تاریخ میلادی رو نشون میده 
> ```
> 
> توی dateedit اینطور میشه

https://github.com/AIKICo/FarsiLibrary

**Comment by HEskandari** [comment]
باید از کنترل XtraFADateEdit استفاده کنید.
