### ISSUE TITLE
.NetCore PLatforms

### ISSUE THREAD

**Issue by matinfathi19** [HEskandari/FarsiLibrary#30]
Is There Any Way To Develop This Components For .NetCore Platforms ?

**Comment by HEskandari** [comment]
@matinfathi19 Which part of it, exactly, do you want to run on .NET Core?

**Comment by matinfathi19** [comment]
Just DatePicker

**Comment by matinfathi19** [comment]
Hi Hadi
Any News?
Is there Any Chance For This Improvment?

**Comment by HEskandari** [comment]
@matinfathi19 Sorry, I thought you mean .NET Core which has no UI component that I can plan to port to. For Xamarin.Form I have no plans to do so either (as I'm personally not using this for any project). I'm open to pull requests though.

**Comment by matinfathi19** [comment]
Yes You thought Right.
For .NetCore WinForms there is not Shamsi DatePicker UI Components.
I Just Ask To have Your Components(DatePicker) In .netCore Projects But they Will Work Just In .NetFrameworks

**Comment by HEskandari** [comment]
Closing.
