### ISSUE TITLE
dev v21.

### ISSUE THREAD

**Issue by mahdi62-dev** [HEskandari/FarsiLibrary#31]
سلام خسته نباشید ممنون از زحماتتون و استفاده ای که ما از برنامه شما می کنیم
جسارتا در ورژن dev 21.2 به بعد بعد از فوکوس در تاریخ ، تاریخ به میلادی نشان داده میشود.
ممنون میشم کمک بفرمائید.

**Comment by HEskandari** [comment]
That version is not supported and there's no plan to support it at the time being.
